[package]
name = "simath"
version = "0.1.0"
edition = "2021"
description = "Simple geometry and math library for my projects"
authors = ["Multirious"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

